######################## default configuration ####################
baseURL = "https://www.mantracoaching.in/"
title = "Mantra Coaching Bhopal"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-YJY1MFRGW7" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true